### ISSUE TITLE
Fake Bookmarking issue #1

### ISSUE THREAD

**Issue by briandesigns** [Equiis/words#2]
# **issue**

bookmarked lessons are not being saved to disk
# **to reproduce the bug**
1. kill the application if not already
2. start the app
3. under the lessons tab, tab the star (bookmark)  button of any one lesson.
4. do any operation in the app except for going to the Bookmarks tab
5. press the android menu button
6. kill the app
7. start the app again
8. go to bookmarks tab
9. (the lesson that was just bookmarked is not present)

In fact, the only way to save a bookmark is to visit the bookmarks tab at least once before the app is killed.

@naerymdan  , contact @briandesigns if more info is required. Thanks

**Comment by naerymdan** [comment]
Sounds good.
